### PR TITLE
Support a structure for countries with multiple gov't levels #212

### PR DESCRIPTION
**Pull request by Abbe98**
This allows contributors to split a country into an unlimited(not really tested beyond two) set of levels. The United Kingdom is provided as an example but others should maybe be split as well(Russia?).

Known end-user issues:

 - [x] The lower level pages render in the wrong location because `/` in their rendering path is replaced with `_`. 
 - [x] The "Federal subjects" title is rendered on a different level than the details icon
 - [x] The map "list" renders all levels not only the top one
 - [x] The country list includes both countries and any lower levels
 - [ ] Even if you are on a third level the title will say "Federal subjects" (if this ever becomes an issue lets find a more generic title)
 - [ ] The statistics page shows all levels (maybe a feature?)
 - [x] The statistics page's country counter is affected by non-top levels 
 - [ ] The lower levels lack a button to navigate to the top level

Implementation issues:

- [x] the federal subjects are not defined in `countries.rq` which would make a lot more of sense
- [ ] The `"Scotland|scotland,Wales|wales"` syntax for defining subjects aren't very nice
- [x] `ge (len (split $m.safeName "/")) 2` is a rather horrifying hack to write a `contains` function

### CODE REVIEW

**Comment by Ainali** [comment]
I added a commit with styling for the "Federal subjects". Now, it won't be an H2, but I think that can be okay anyway.

**Comment by Abbe98** [comment]
You will now need Snowman 0.6.0 to build this branch: https://github.com/glaciers-in-archives/snowman/releases/tag/0.6.0

**Comment by Abbe98** [comment]
I'm quite happy with the implementation now and think that the remaining issues can wait. Updated documentation aside.

**Comment by Ainali** [comment]
> I'm quite happy with the implementation now and think that the remaining issues can wait. Updated documentation aside.

Yes, I too think this is good enough to start with. We could convert the outstanding checkboxes to individual issues to not forget them.

**Review by Ainali — APPROVED** [review]

**Pull request merged**
