### PR TITLE
New design

### PR DESCRIPTION
**Pull request by Abbe98**
- [x] new landing page header design
- [x] new color scheme
- [x] landing page "qoutes"
- [x] rework about page 

Questions:
 - Should the footer be orange or blue? :heavy_check_mark: 
 - What color should the button hover effect be? :heavy_check_mark: 
 - Which image should we use for the landing page header? :heavy_check_mark:

### CODE REVIEW

**Comment by Ainali** [comment]
- I think the footer can stay blue. It will "ground" the page nicely.
- I suggest #094082. I've started  playing with colors in the penpot design system file
- Good question. I didn't have that one in the discussion yet. Until we have a good "disussion" image under CC0, perhaps we can go with something simple like: https://commons.wikimedia.org/wiki/File:Man_with_smartphone_and_laptop_(Unsplash).jpg Mockup below. Not really emotional either, it's slightly technical still, but at least in the right direction and with a human in the image.

new hero

**Comment by Abbe98** [comment]
It looks good to me, it might appear odd on very large screens but it works for now.

**Review by Ainali — APPROVED** [review]
So far so good, I like it!

**Comment by Ainali** [comment]
one comment about the colors in the main heading. You are using orange first and white second instead of white -> orange. Not a big deal, but I think I would prefer the latter.

**Comment by Abbe98** [comment]
Orange links with `#094082` as the background color on hover?

**Comment by Ainali** [comment]
> one comment about the colors in the main heading. You are using orange first and white second instead of white -> orange. Not a big deal, but I think I would prefer the latter.

Hmm, I think I confused myself with the presentation layout. Keep this as is!

**Comment by Ainali** [comment]
> Orange links with `#094082` as the background color on hover?

Sorry, I was ambiguous. I didn't mean in the header, but the text in the splash. And as my last comment, it's good :)

**Comment by Ainali** [comment]
Suggestion, can the first orange section be it's own class with only 20 px padding? And perhaps lose the bottom margin of the buttons there as well so that it looks something like this:

Skärmbild från 2021-09-25 00-02-37

**Comment by Ainali** [comment]
It looks really good!

It just the last section (Acknowledgements) on the about that has the same section color as the one before.

**Review by Ainali — APPROVED** [review]
Beautiful!

**Comment by Abbe98** [comment]
I left out the changes to the "start the conversation now" section as it looked odd on smaller screens and would need more work.

**Pull request merged**
