### PR TITLE
Add spell checker and workflow

### PR DESCRIPTION
**Pull request by Ainali**
Adding our first test! :tada:

### CODE REVIEW

**Review by Abbe98 — COMMENTED** [review]
Given the many allow-listed words already needed, I would expect that false-positives would be very common. Therefore, this action should maybe, instead of failing add a helpful comment mentioning the allow list?

**Comment by Ainali** [comment]
I don't know how to get an action to add that comment, but the test will say which word is not in the list. Is that enough? Or should we add some more documentation that explains the list?

**Comment by Abbe98** [comment]
My thinking is that it might not be a very good first time experience contributing if there is a false positive test requiring additional changes. An option could be to put the action on a schedule, which would move the burden from contributors to maintainers?

**Comment by Ainali** [comment]
If there are false positives, it's not great, true, but I am not sure that there will be many more false positives, as the jargon related to Wikidata and SPARQL is mostly added already. If a contribution has other jargon that is not in aspell, I think it is worth even for new contributors to start thinking if a simpler language can be used.

And also, the burden isn't solely on the contributor when a test fails on PR, but also on the maintainers to help get it right before merging.

**Comment by Abbe98** [comment]
I'm convinced to try it out, but if it ends up producing false positives to newcomers I think we should put it on a schedule.

**Review by Abbe98 — APPROVED** [review]

**Pull request merged**
