### PR TITLE
🇮🇪 Add Ireland

### PR DESCRIPTION
**Pull request by RVA2869**
# Description
Adding a small amount of Irish data. (Hoping this will encourage people to add more data from Ireland)

## Issue Reference

Fixes #(issue)

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Code refactor

## Checklist

Please **ensure** the following before submitting the PR:

- [x] I have **tested** the changes locally, and they work as expected.
- [x] The code follows the project's coding standards and conventions.
- [x] Any **query changes** have been verified and are working correctly.

### CODE REVIEW

**Comment by Ainali** [comment]
I can't see a project page on Wikidata (I would have expected it on https://www.wikidata.org/wiki/Wikidata:WikiProject_Govdirectory/Ireland ). Am I missing it somehow?

**Comment by RVA2869** [comment]
Yes when i was making the project page I had a "great idea" to use the official name. Note the sarcasm ;-) [[Wikidata:WikiProject Govdirectory/Republic of Ireland]
](https://www.wikidata.org/wiki/Wikidata:WikiProject_Govdirectory/Republic_of_Ireland)

**Comment by Ainali** [comment]
Perhaps we should either move the page there, or also use the same name here, so that it is consistent and easier to find?

**Review by Ainali — APPROVED** [review]
Good to go!

**Pull request merged**
