### PR TITLE
add script to check the expected result count against the actual result

### PR DESCRIPTION
**Pull request by Abbe98**
Usage example:
Screenshot from 2024-07-19 15-37-05

### CODE REVIEW

**Comment by Abbe98** [comment]
In the best of worlds we would have something like this on Wiki, similar to auto updating Listeria lists but in the meanwhile...

**Comment by RVA2869** [comment]
@Abbe98 FYI Scotland is missing.

interesting, all failures are "within the margin", only in Malta many items are missing.

**Comment by Abbe98** [comment]
Nice catch @RVA2869!

**Comment by Ainali** [comment]
I'm trying to run it, but get this:

```
Traceback (most recent call last):
  File "/scripts/check-expected-results-count.py", line 56, in <module>
    verify_result_counts(folder_path, endpoint)
  File "/scripts/check-expected-results-count.py", line 33, in verify_result_counts
    with open(file_path, "r") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'queries/generators/queries/generators/united-kingdom.rq'
```

**Comment by Ainali** [comment]
> only in Malta many items are missing

Looks like one user [https://www.wikidata.org/w/index.php?title=Special:Contributions&end=2024-06-01&namespace=0&start=2024-05-30&tagfilter=&target=EnriqueTabone&offset=&limit=500 decided that] the local councils should just be towns instead.

**Comment by Abbe98** [comment]
Must be squash merged.

**Review by Ainali — APPROVED** [review]
Super useful!

**Comment by Ainali** [comment]
@Abbe98 I missed the squash merge. Is that a problem?

**Pull request merged**
