### PR TITLE
❌  Less Twitter more X

### PR DESCRIPTION
**Pull request by RVA2869**
I'll leave it in draft until this question is resolved.

#294

### CODE REVIEW

**Comment by Ainali** [comment]
Thanks for getting this moved along! It would be nice if we had some provenance of the image so that we know that it is aligned with our license. Do you think you could add that?

**Comment by RVA2869** [comment]
> Thanks for getting this moved along! It would be nice if we had some provenance of the image so that we know that it is aligned with our license. Do you think you could add that?

It is the official X of x.com ([Brand toolkit](https://about.x.com/en/who-we-are/brand-toolkit)). With a black circle (homemade)
I haven't found anything about how to use or not use the logo.

**Comment by Ainali** [comment]
I would say that this PR would solve #294 for now. If we want to make another change later, we can create a new more specified issue later or reopen it.

**Review by Ainali — APPROVED** [review]
Looks good!

**Pull request merged**
