### PR TITLE
Exclude end dated accounts from the query

### PR DESCRIPTION
**Pull request by viveknshah**
Details in #246

### CODE REVIEW

**Comment by viveknshah** [comment]
To fix #83

**Comment by viveknshah** [comment]
@Ainali Apologies for that - hopefully this makes it easy for you. Still getting my head around rebasing and branching.

**Comment by Ainali** [comment]
Thanks for the effort, I'm testing it locally now!

**Review by Ainali — APPROVED** [review]
I finally had the time to test this and it works as expected!

**Comment by viveknshah** [comment]
Thanks! I actually had no clue about SPARQL and to solve for this, got a chance to play around and understand its power !

**Comment by Ainali** [comment]
Ah, that's great to hear! Yes, SPARQL is really fun and exploring Wikidata that has so much different content is a fantastic way to learn both the technical side and about the world.

**Pull request merged**
