### PR TITLE
Added lang attribute to literals in wikidata

### PR DESCRIPTION
**Pull request by toukirkhan**
Added lang attribute to literals as asked in the issue wherever a non-english literal could be expected. And made some indentation changes.

### CODE REVIEW

**Comment by Ainali** [comment]
Good start, but #84 was meant to tag all literals in all files. The example shown in the issue is just an example and not the entire change needed.

**Comment by toukirkhan** [comment]
okay so I have to add literals in whichever file available right? Do I need to add tag unordered lists literals too because it will be way too much complicated?

**Comment by toukirkhan** [comment]
@Ainali I have made some more changes please check

**Review by Abbe98 — APPROVED** [review]
Looks good! :rocket:

**Pull request merged**
