### PR TITLE
🖼 simplify country pages

### LINKED ISSUE #179: Prominent "error message"
### Description

The "Found an error?" message is quite big and and prominent. In combination with the background color I get the feeling that I'm met with an error message. Perhaps it could be rephrased to something along the lines of "Improve this data"?
bild

### PR DESCRIPTION
**Pull request by RVA2869**
fixes #179

### CODE REVIEW

**Comment by Ainali** [comment]
I would rather see the solution of #179 to go in the direction of the discussion in it. That is, creating consistent behavior across countries and organizations.

Just removing the option for simply flagging that something is wrong for those who don't know how Wikidata works seems to be complicating their user experience, even though the page looks simpler.

**Comment by RVA2869** [comment]
Then consider it temporary *; I made this commit to equalize the difference in design between the country- and the organization pages.

*until someone has a definitive solution to this issue.

**Comment by Ainali** [comment]
I try to build your branch but I get this error:

```
Error: Failed to render page at site/austria/index.html Error: html/template:country-page.html: "\"" in attribute name: "btn-list\">\n                <a cl"
```

**Comment by Ainali** [comment]
Now it builds, but the links from the Wikidata button on all countries are the same. `https://www.wikidata.org/wiki/`. If it could go to the country page, that would be good.

**Comment by Abbe98** [comment]
A massive improvement, thank you! 🚀

**Pull request merged**
