### PR TITLE
Update country-page.html

### PR DESCRIPTION
**Pull request by toukirkhan**
Added a lang attribute

### CODE REVIEW

**Comment by toukirkhan** [comment]
Please  tell me if this is correct

**Comment by Abbe98** [comment]
The approach is right, but I think we should do it more across the code base rather than just introduce it in one place.

**Comment by toukirkhan** [comment]
Can you just guide me a bit about the pages where it needs to be done, I am ready to do it. Thanks!

**Comment by toukirkhan** [comment]
I am creating a new pull request from another fork.

**Pull request closed without merging**
