### PR TITLE
🖼 Set img height for social icons.

### PR DESCRIPTION
**Pull request by RVA2869**
#96

### CODE REVIEW

**Review by Ainali — APPROVED** [review]
This looks good to me!

**Comment by Ainali** [comment]
@RVA2869 could you make the file changes in a separate PR, please? This would make it easier to understand what happened based on the title of it.

**Comment by RVA2869** [comment]
@Ainali I was messing around with webp - changes are reverted

**Comment by Abbe98** [comment]
@RVA2869 thank you! 🌟

**Pull request merged**
