### PR TITLE
Optimize/compress static images

### PR DESCRIPTION
**Pull request by RVA2869**
Fixes: #147 

Changes made: I converted the JPG images to Webp and compressed them using TinyPNG.
Resize helicopter and factory image to 450 x 300.

### CODE REVIEW

**Comment by Ainali** [comment]
Thanks for working on this @RVA2869! I think it looks fine when I serve this locally. The only thing I am unsure of is whether external services that would see the og-banner can handle webp or not. If that's the case, then I think this is ready to go.

**Comment by RVA2869** [comment]
> Thanks for working on this @RVA2869! I think it looks fine when I serve this locally. The only thing I am unsure of is whether external services that would see the og-banner can handle webp or not. If that's the case, then I think this is ready to go.

@Ainali The JPG version is currently still available. (because I didn't find where it was used) What external services are you talking about? Browser-wise: only Internet Explorer does not support this format. [https://caniuse.com/webp](https://caniuse.com/webp)

**Comment by Ainali** [comment]
It's used in [templates/layouts/layout.html](https://github.com/govdirectory/website/blob/8733db764b59b095ef6c495f147e9021cc0bfba2/templates/layouts/layout.html#L38), but really only rendered on external sites as a link preview.

**Comment by Ainali** [comment]
There is no specific format mentioned in the [Open Graph Protocol](https://ogp.me/). However, in the blog post [Can you use a WebP file as an Open Graph Protocol image?](https://www.ctrl.blog/entry/webp-ogp.html) there is a nice table, and based on that, I think it is too early to swap it. So if you just remove that file from the pull request, I am happy to approve it.

**Review by Ainali — APPROVED** [review]
Thanks for the work! It's remarkable how much lighter the webp images are.

**Comment by Abbe98** [comment]
Superb! 🎨

**Pull request merged**
