### PR TITLE
Visualize the countries govdirectory/website#200 :world_map: 

### PR DESCRIPTION
**Pull request by Abbe98**
Mostly a vacation concept. :palm_tree: 

- [x] The map should be moved to the country page(behind a tab? in a modal?)
- [x] Drop CDN usage
- [x] Errors and loading indicators?
- [x] colors / design?

### CODE REVIEW

**Comment by Abbe98** [comment]
@Ainali oh yes, and it makes a good point here as we need to make sure it's possible to link to the tab/model or what ever solution we go for.

**Comment by Abbe98** [comment]
One problem is that if we want to make it possible to link to this page we must make it a separate page to make it reliable.

**Comment by Ainali** [comment]
Yes, but is that really a problem? The link from the countries page can go to `countries/map.html` and then that page can just have a link back to the list again somewhere.

**Review by Ainali — APPROVED** [review]
Very cool!

**Comment by Abbe98** [comment]
Will deploy once I'm back from vacation  (back from vacation wifi).

**Pull request merged**
