### PR TITLE
Concise text (as tsv) to download

### PR DESCRIPTION
**Pull request by viveknshah**
Fix for #145 
Considering space - kept it at (as tsv) suffix to the Download so it is intuitive to the user.

### CODE REVIEW

**Review by Ainali — APPROVED** [review]
Looks good to me! What do you think @Abbe98 ?

**Comment by Abbe98** [comment]
I have a slight preference towards dropping the "as" if we wrap it in parentheses.

**Review by Abbe98 — CHANGES_REQUESTED** [review]
"tsv" should be uppercase to make sure it reads okay to screen readers.

**Review by viveknshah — COMMENTED** [review]
Made the updates

**Comment by Abbe98** [comment]
Thank you @viveknshah! :star2:

**Pull request merged**
